# Import Module

In [1]:
import numpy as np
import torch

# Tensors

## Definisi

- Tensor adalah struktur data berbentuk array multidimensi yang dapat berjalan pada akselerator peragkat keras, seperti GPU dan TPU.
- Secara dasar mirip dengan Numpy array, tapi memiliki kelebihnandapat diproses pada akselerator, seperti GPU dan TPU.
- Dioptimalkan untuk diferensiasi otomatis.

## Inisialisasi

### List Python

In [2]:
data_list = [[1, 3], [5, 7]]
list_tensor = torch.tensor(data_list)

list_tensor

tensor([[1, 3],
        [5, 7]])

### Numpy Array

In [3]:
data_numpy = np.array([[1, 3], [5, 7]])
numpy_tensor = torch.tensor(data_numpy)

numpy_tensor

tensor([[1, 3],
        [5, 7]], dtype=torch.int32)

### From Another Tensor

In [4]:
x_ones = torch.ones_like(numpy_tensor)
x_ones

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [5]:
x_rand = torch.rand_like(x_ones, dtype=torch.float)
x_rand

tensor([[0.8574, 0.7484],
        [0.9477, 0.1451]])

### With random or constant value

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [7]:
rand_tensor

tensor([[2.2566e-01, 7.6470e-01, 2.7710e-04],
        [8.9522e-02, 9.6760e-01, 3.4859e-01]])

In [8]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Tensor Attribute

In [10]:
tensor = torch.rand((2, 3))

print(f"shape    : {tensor.shape}")
print(f"datatype : {tensor.dtype}")
print(f"device   : {tensor.device}")

shape    : torch.Size([2, 3])
datatype : torch.float32
device   : cpu


## Operation

# Check device

In [11]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Accessing

In [12]:
tensor = torch.rand((4, 4))
print(f"Tensor       : {tensor}")
print(f"First row    : {tensor[0]}")
print(f"Second row   : {tensor[1]}")
print(f"Third row    : {tensor[2]}")
print(f"First column : {tensor[:, 0]}")
print(f"Last column  : {tensor[:, -1]}")

Tensor       : tensor([[0.4094, 0.1479, 0.5321, 0.4419],
        [0.2428, 0.4851, 0.3993, 0.1699],
        [0.8450, 0.3875, 0.7178, 0.7858],
        [0.7315, 0.8624, 0.5436, 0.4030]])
First row    : tensor([0.4094, 0.1479, 0.5321, 0.4419])
Second row   : tensor([0.2428, 0.4851, 0.3993, 0.1699])
Third row    : tensor([0.8450, 0.3875, 0.7178, 0.7858])
First column : tensor([0.4094, 0.2428, 0.8450, 0.7315])
Last column  : tensor([0.4419, 0.1699, 0.7858, 0.4030])


## Concate Tensor

In [13]:
## Row DDirection
concate_tensor = torch.cat([tensor, tensor], dim=0)
concate_tensor

tensor([[0.4094, 0.1479, 0.5321, 0.4419],
        [0.2428, 0.4851, 0.3993, 0.1699],
        [0.8450, 0.3875, 0.7178, 0.7858],
        [0.7315, 0.8624, 0.5436, 0.4030],
        [0.4094, 0.1479, 0.5321, 0.4419],
        [0.2428, 0.4851, 0.3993, 0.1699],
        [0.8450, 0.3875, 0.7178, 0.7858],
        [0.7315, 0.8624, 0.5436, 0.4030]])

In [14]:
## Column DDirection
concate_tensor = torch.cat([tensor, tensor], dim=1)
concate_tensor

tensor([[0.4094, 0.1479, 0.5321, 0.4419, 0.4094, 0.1479, 0.5321, 0.4419],
        [0.2428, 0.4851, 0.3993, 0.1699, 0.2428, 0.4851, 0.3993, 0.1699],
        [0.8450, 0.3875, 0.7178, 0.7858, 0.8450, 0.3875, 0.7178, 0.7858],
        [0.7315, 0.8624, 0.5436, 0.4030, 0.7315, 0.8624, 0.5436, 0.4030]])

## Arithmatic

In [15]:
tensor = torch.arange(0, 9).reshape(3, 3)
tensor

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

### Matrix Multiplication

In [16]:
mat_mul_tensor = tensor @ tensor
mat_mul_tensor

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [17]:
mat_mul_tensor = tensor.matmul(tensor)
mat_mul_tensor

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

### Element-Wise Product

In [18]:
elemwise_prod = tensor * tensor
elemwise_prod

tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])

In [19]:
elemwise_prod = tensor.mul(tensor)
elemwise_prod

tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])

### Aggregation

In [20]:
min_value = tensor.min()
max_value = tensor.max()
sum_value = tensor.sum()
mean_value = tensor.to(dtype=torch.float).mean()
median_value = tensor.median()

print(f"Min: {min_value}")
print(f"Max: {max_value}")
print(f"Sum: {sum_value}")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")

Min: 0
Max: 8
Sum: 36
Mean: 4.0
Median: 4


In [21]:
print(f"Add: {tensor.add_(5)}")
print(f"Sub: {tensor.sub_(5)}")
print(f"Mul: {tensor.mul_(5)}")
print(f"Div: {tensor.to(dtype=torch.float, device=device).div_(5)}")
print(f"Rem: {tensor.to(dtype=torch.float).remainder_(5)}")

Add: tensor([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]])
Sub: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Mul: tensor([[ 0,  5, 10],
        [15, 20, 25],
        [30, 35, 40]])
Div: tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], device='cuda:0')
Rem: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## Tensor to Numpy

In [22]:
tensor = torch.ones(3, 3)
type(tensor)

torch.Tensor

In [23]:
tensor_to_numpy = tensor.numpy()
type(tensor_to_numpy)

numpy.ndarray

## Numpy to Tensor

In [24]:
numpy = np.ones(5)
type(numpy)

numpy.ndarray

In [25]:
numpy_to_tensor = torch.from_numpy(numpy)
type(numpy_to_tensor)

torch.Tensor