# Loop Function

- Pada proses pelatihan model, model akan dilatih melalui iterasi berkali-kali dengan tujuan agar loss yang dihasilkan pada proses training berkurang.
- Proses iterasi ini disebut **training loop**.
- Jumlah iterasi ini juga biasa disebut **epoch**. **Epoch** merupakan salah satu hyperparameter.
- Jumlah **epoch** telah ditentukan sebelumnya.

# Loop Function in Pytorch

## Import Modules

In [1]:
import torch

from torch import nn, optim
from torch.utils.data import DataLoader, TensorDataset
from torchmetrics.functional import r2_score

C:\Users\62821\.conda\envs\dl_with_me\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Dataset

- Dataset yang digunakan adalah kumpulan bilangan yang dibuat menggunakan random generator.
- Variabel X (fitur) berukuran 50 baris dan 4 kolom dan variabel y (target) berukuran 50 baris dan 1 kolom.

In [2]:
torch.manual_seed(42)

X = torch.rand(size=(20, 4))
y = torch.rand(size=(20, 1))

print(f"X:\n{X}\n")
print(f"y:\n{y}")

X:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155]])

y:
tensor([[0.2418],
        [0.1591],
        [0.7653],
        [0.2979],
        [0.8035],
        [0.3813],
        [0.7860],
        [0.1115],
        

## Tensor Dataset

- Variabel X dan y digabungkan dengan menggunakan modul `TensorDataset`.
- Hal ini dilakukan untuk mempermudah mengambil nilai dari variabel X dan y pada saat proses pelatihan model.

In [3]:
tensor_dataset = TensorDataset(X, y)

tensor_dataset.tensors

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317],
         [0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895],
         [0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447],
         [0.5315, 0.1587, 0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666],
         [0.9811, 0.0874, 0.0041, 0.1088],
         [0.1637, 0.7025, 0.6790, 0.9155]]),
 tensor([[0.2418],
         [0.1591],
         [0.7653],
         [0.2979],
         [0.8035],
         [0.3813],
         [0.7860],
     

## DataLoader

- `DataLoader` digunakan untuk menerapkan **batching** dan **shuffle** pada dataset.

In [4]:
dataloader = DataLoader(tensor_dataset, batch_size=5, shuffle=True)
next(iter(dataloader))

[tensor([[0.5315, 0.1587, 0.6542, 0.3278],
         [0.9408, 0.1332, 0.9346, 0.5936],
         [0.8860, 0.5832, 0.3376, 0.8090],
         [0.7890, 0.2814, 0.7886, 0.5895],
         [0.6532, 0.3958, 0.9147, 0.2036]]),
 tensor([[0.2331],
         [0.7653],
         [0.2477],
         [0.3725],
         [0.9578]])]

## Model

In [5]:
model = nn.Sequential(
            # layer 1 (4 neurons) to layer 2 (2 neurons) with ReLU
            nn.Linear(4, 2),
            nn.ReLU(),
            
            # layer 2 (2 neurons) to layer 3 (1 neurons) with Sigmoid
            nn.Linear(2, 1),
            nn.Sigmoid(),
        )

model

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=1, bias=True)
  (3): Sigmoid()
)

## Loss Function

In [6]:
mse_loss = nn.MSELoss()

mse_loss

MSELoss()

## Optimizer

In [7]:
sgd_optimizer = optim.SGD(model.parameters(), lr=1)

sgd_optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

## Loop Function

In [8]:
def loop_fn(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    loss_batches = []
    r2_score_batches = []
    
    for batch, (X, y) in enumerate(dataloader):
        # Forward Propagation
        pred = model(X)
        loss = loss_fn(pred, y)
        r_square = r2_score(pred, y)
        
        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        # Calculate loss each batch
        loss = loss.item()
        loss_batches.append(loss)
        
        # Calculate r-square each batch
        r_square = r_square.item()
        r2_score_batches.append(r_square)
        
        current_batch = (batch + 1) * len(X)
        
        # Show Log
        print(f"batch {batch + 1}: [{current_batch:>3d}/{size:>3d}] | r2-score: {r_square:>8f} | loss: {loss:>7f}")
    print(f"R2 score  : {sum(r2_score_batches) / len(r2_score_batches)}")
    print(f"RMSE loss : {(sum(loss_batches) / len(loss_batches))**0.5}")
    
# Run Loop Function
epochs = 5

for epoch in range(epochs):
    print(f"Epoch {epoch + 1}")
    loop_fn(dataloader, model, mse_loss, sgd_optimizer)
    print("-" * 60, end="\n\n")
print("Done!")

Epoch 1
batch 1: [  5/ 20] | r2-score: -0.001476 | loss: 0.132229
batch 2: [ 10/ 20] | r2-score: -1.386093 | loss: 0.064782
batch 3: [ 15/ 20] | r2-score: 0.003590 | loss: 0.085312
batch 4: [ 20/ 20] | r2-score: -0.079285 | loss: 0.058576
R2 score  : -0.36581578850746155
RMSE loss : 0.29193296597424057
------------------------------------------------------------

Epoch 2
batch 1: [  5/ 20] | r2-score: -0.054929 | loss: 0.083434
batch 2: [ 10/ 20] | r2-score: -0.190645 | loss: 0.067922
batch 3: [ 15/ 20] | r2-score: -6.483576 | loss: 0.088354
batch 4: [ 20/ 20] | r2-score: -0.109595 | loss: 0.099401
R2 score  : -1.7096863985061646
RMSE loss : 0.2911661673964669
------------------------------------------------------------

Epoch 3
batch 1: [  5/ 20] | r2-score: -0.013475 | loss: 0.122823
batch 2: [ 10/ 20] | r2-score: -10.520777 | loss: 0.056351
batch 3: [ 15/ 20] | r2-score: -0.025636 | loss: 0.097660
batch 4: [ 20/ 20] | r2-score: -0.095159 | loss: 0.054186
R2 score  : -2.6637615561485